import Head from 'next/head'

export default function Home() {

  const URL = `https://api.openweathermap.org/data/2.5/weather?q=dubai&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`


  return (
    <div>
      <Head>
        <title>Weather App - NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hey!</h1>
    </div>
  )
}
